name: Deploy

on:
  push:
    tags:
      - '**'

jobs:
  deploy:
    name: Upload Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.36", "3.38", "40.0"]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build
      id: build
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ github.repository }}
        tags: ${{ matrix.version == '40.0' && '40.0 latest' || matrix.version }}
        dockerfiles: ./Dockerfile.${{ matrix.version }}
    - name: Push
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build.outputs.image }}
        tags: ${{ steps.build.outputs.tags }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io
